### ISSUE TITLE
Bind [()] input field with component property

### ISSUE THREAD

**Issue by nmrt** [Aksana-Tsishchanka/angular2#3]
On Find click - console.log input value

https://github.com/Aksana-Tsishchanka/angular2/blob/941a7131923cc0ce5d974d2388779f73efbb928a/app/components/search/search.component.ts#L8

**Comment by nmrt** [comment]
https://angular.io/guide/template-syntax#two-way-binding---
https://angular.io/guide/template-syntax#ngmodel---two-way-binding-to-form-elements-with-ngmodel

**Comment by Aksana-Tsishchanka** [comment]
done
