### ISSUE TITLE
Learn some lifecycle hooks

### ISSUE THREAD

**Issue by nmrt** [Aksana-Tsishchanka/angular2#5]
Try to declare courses without  array then assign empty array in constructor and after that assign fake values on ngOnInit hook.

Place console.log statement in hooks (https://angular.io/docs/ts/latest/guide/lifecycle-hooks.html) to understand ordering.

https://github.com/Aksana-Tsishchanka/angular2/blob/941a7131923cc0ce5d974d2388779f73efbb928a/app/components/course/courseList.component.ts#L22

**Comment by Aksana-Tsishchanka** [comment]
done
